### ISSUE TITLE
Colors mode not working

### ISSUE THREAD

**Issue by mjuzikfrik** [AnKingMed/The-KING-of-Button-Add-ons#1]
Hello,

I'd like to report that color mode isn't working for me.

Windows 10 1909 x64
Anki 2.22

![Screenshot_1](https://user-images.githubusercontent.com/16630872/76340941-a6ec3500-62fc-11ea-837c-31d5e271e792.png)

**Comment by AnKingMed** [comment]
hmm I'm not able to replicate this.  Can you try it again with no other add-ons installed? (just drag and drop them to a folder on your desktop)

**Comment by mjuzikfrik** [comment]
That didn't change anything, but it works when I turn off anki's night mode. So:
anki's night mode (from 2.20) - not working
bright mode - working

**Comment by AnKingMed** [comment]
Have you tried this on .20 or .21?

**Comment by AnKingMed** [comment]
Try deleting this line: "background-color: #3a3a3a!important;" and let me know if that fixes it:

https://github.com/AnKingMed/The-KING-of-Button-Add-ons/blob/1a9cab46e4991a7de869d5b43c0c57757e9d659a/nightmode_buttons.py#L216

**Comment by mjuzikfrik** [comment]
Neither going back to .20 or .21 nor deleting that line changed anything. I think I'd just stick to hover mode.

**Comment by AnKingMed** [comment]
Super weird. I'll have to get on a windows and test some stuff out. I can't figure it out for now sorry

**Comment by AnKingMed** [comment]
Just pushed an update. Let me know if that doesn't fix the problem

**Comment by mjuzikfrik** [comment]
That did the trick!. Thank you. :)
