### ISSUE TITLE
No Buttons, Connection Refused

### ISSUE THREAD

**Issue by Destaq** [AnKingMed/The-KING-of-Button-Add-ons#13]
I installed the add-on with the latest version of Anki, and restarted.

Button icons stayed the same, and I got the following error message:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-10-14 09:10:58

failed to open '/var/folders/9l/8zpt0mq90lb6t4xn25mbkfgw0000gq/T/discord-ipc-0': [Errno 61] Connection refused
```

**Comment by AnKingMed** [comment]
I am not sure what this error has to do with this add-on. This addon doesn't affect connection at all. Does the error occur even when this add-on is toggled off?

**Comment by Destaq** [comment]
My bad, I thought it was this add-on.

On another note, does this add-on support customizing the home screen buttons?
![image](https://user-images.githubusercontent.com/61620873/96005944-41859700-0e3d-11eb-9f5b-6dd873380a0b.png)

**Comment by AnKingMed** [comment]
Yes you could customize them, but you would need to do so by editing the python file
