### ISSUE TITLE
The tooltip for Again is appearing on extreme right of screen

### ISSUE THREAD

**Issue by QueenEvanescence** [AnKingMed/The-KING-of-Button-Add-ons#15]
The tooltip of the other three are appearing over the button on being clicked but again appears on the extreme right for some weird reason. I have an extended screen but i dont see how that can cause this issue
<img width="1920" alt="2021-09-21" src="https://user-images.githubusercontent.com/88851719/134109879-9a4ddfc0-733e-413c-9421-f51b59edf584.png">

**Comment by AnKingMed** [comment]
This is just a part of the add-on unfortunately. It uses center of the screen to adjust where the popups are. In the config of the add-on you can adjust this with:
`    "confirmation x-offset": 3,
    "confirmation y-offset": 0,`
