### ISSUE TITLE
Incompatible with fill the blanks - multiple typeclose support

### ISSUE THREAD

**Issue by Quip13** [AnKingMed/The-KING-of-Button-Add-ons#2]
Not sure if this is your issue or the other addons issue, but your wrap doesn't work if I have both enabled

I've been having similar issues with my own add-on development with this add-on  and I'm not sure why it's happening. I'd be nice to have another set of eyes on it to figure out what's going on

**Comment by AnKingMed** [comment]
I'll look into it.  I don't have very much coding experience to be honest so I don't know that my opinion is going to be worth very much

**Comment by Quip13** [comment]
Well that makes 2 of us :)

I suspect it’s something to do with the fact that you wrap Reviewer (the parent class) and the other addon wraps mw.reviewer (the instance)
Idk what’s correct or why it breaks

**Comment by Quip13** [comment]
I think I'm onto something...
if I figure it out I might submit a PR

**Comment by AnKingMed** [comment]
Sounds good to me! Thanks!

**Comment by Quip13** [comment]
Alright I'm still figuring out github but I submitted a PR with changes that fixed my issues
And thanks for building this - it's a big improvement over the other button addons

**Comment by AnKingMed** [comment]
Should be fixed now. Thanks for the PR.
