### ISSUE TITLE
Colors show if you press buttons when the question is showing

### ISSUE THREAD

**Issue by Ooglogput** [AnKingMed/The-KING-of-Button-Add-ons#4]
I'm sure you're aware of this already, since it's even visible in the animation on the main page, but I think it deserves an issue. 

![image](https://user-images.githubusercontent.com/1039490/76365841-a073b280-6328-11ea-8794-7d7b580da6b8.png)

**Comment by AnKingMed** [comment]
I am aware of it, just forgot to fix it! Will do in the next update!
