### ISSUE TITLE
Configuration color not working since latest update

### ISSUE THREAD

**Issue by adix03** [AnKingMed/The-KING-of-Button-Add-ons#6]

**Comment by AnKingMed** [comment]
You can't change any of the colors?  Or which colors aren't working? Also can you provide which version of Anki you are on and operating system?

**Comment by adix03** [comment]
None of the colors are changing. I'm using 2.1.22 beta 1 on windows 10

**Comment by AnKingMed** [comment]
I can't recreate your problem here. Can you give me more details on what you're doing?  Are you on nightmode or normal mode? Which color are you trying to change?  There are color options for nightmode and normal mode so can you change both and then let me know if it works?   You can also send me pictures of your config and what your buttons look like and that would be helpful

**Comment by ijgnd** [comment]
@adix03: It's great that you inform the developer on github where he can answer. As someone who has released some add-ons I must say: It really helps to try to answer *all* questions the developer poses even if you think that they are irrelevant. E.g. I see no answer for "Did you restart anki?". You should also post the full config and exactly describe step by step how to reproduce the problem and a screenshot.

&nbsp;

I can't reproduce the problem on my pc. Details about my system copied from main window ->help->About ->copy debug info 


    Anki 2.1.22 (2f028678) Python 3.7.3 Qt 5.13.2 PyQt 5.13.2
    Platform: Linux
    Flags: frz=False ao=True sv=2
    Add-ons, last update check: 2020-03-11 14:44:34
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    The KING of Button Add-ons ['374005964', 2020-03-11T11:03, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    374005964
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['reviewer_more_answer_buttons-anki21', 0, 'None', mod]


My config: I made the good button blue (I put "CHANGED" into the relevant lines so that you quickly see them here, but the string "CHANGED" is not in my add-on config):

    {
        "AgainColor": "red",
        "EasyColor": "#61a8ff",
        "GoodColor": "#0000ff",  CHANGED
        "HardColor": "orange",
        "Nightmode_AgainColor": "#ff6961",
        "Nightmode_EasyColor": "#61a8ff",
        "Nightmode_GoodColor": "#0000ff",  CHANGED
        "Nightmode_HardColor": "#ffb861",
        "answer button width": "Full",
        "border radius": "3",
        "button color": "colors",  CHANGED
        "button font size": "S",
        "button height": "S",
        "button width": "S",
        "confirmation": true,
        "confirmation time": 450,
        "confirmation x-offset": 0,
        "confirmation y-offset": 0,
        "style main screen buttons": true
    }

**Comment by adix03** [comment]
I feel sorry for not answering in detail. Yes, I did restart Anki a few times but it didn't take effect.

Debug info:
```
    Anki 2.1.22 (131d37dc) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-03-11 08:35:08
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Browser MaximizeHide TableEditor ['1819291495', 2020-01-13T10:33, 'None', mod]
    Browser Resizer ['1435775540', 2020-02-08T06:09, 'None', '']
    Correct Answers Graph ['993120073', 2020-01-13T10:33, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2020-01-18T19:07, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-16T21:14, 'None', '']
    Deck Counts NowLater ['1836212767', 2019-07-11T00:46, 'None', '']
    Ease Factor Histogram ['494944895', 2019-04-30T21:55, 'None', '']
    Edit Field During Review ['1020366288', 2020-01-30T10:08, 'None', '']
    Extended Overview Stats ['738807903', 2019-01-06T02:12, 'None', '']
    Field History ['1247884413', 2019-04-10T14:35, 'None', '']
    Five Finger Silver New Answer Button Graph ReLrn Stats ReMemorize Plan9-0 ['2047355215', 2019-06-04T23:57, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2019-07-23T15:08, 'None', '']
    Increase autosave frequency ['786971082', 2018-08-12T04:03, 'None', '']
    Mini Format Pack ['295889520', 2019-05-26T10:30, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2019-06-13T11:31, 'None', '']
    Review Heatmap ['review_heatmap', 2018-10-29T03:36, 'None', '']
    Reviewer to Browser choosing what to display ['1555020859', 2020-03-11T03:18, 'None', mod]
    Stats Overview Pie Graph with Distinct Learning and-or Relearning Sections ['1828603731', 2019-03-28T02:08, 'None', mod]
    The KING of Button Add-ons ['374005964', 2020-03-11T08:13, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1020366288 1247884413 1435775540 1555020859 1819291495 1828603731 1836212767 1988760596 2047355215 225180905 266436365 295889520 374005964 494944895 738807903 786971082 861263371 993120073
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Answer Confirmation for 21 ['1354051622', 2019-04-04T18:24, 'None', '']
    Button Colours Good Again ['2494384865', 2020-02-09T17:48, 'None', mod]
    Directly review without going through overview page ['1024346707', 2019-11-07T14:06, 'None', '']
    Enhance main window ['877182321', 2020-02-16T08:21, 'None', mod]
```

My config:
```
{
    "AgainColor": "#C00", CHANGED
    "EasyColor": "#00f", CHANGED
    "GoodColor": "#070", CHANGED
    "HardColor": "darkgoldenrod", CHANGED
    "Nightmode_AgainColor": "#ff6961",
    "Nightmode_EasyColor": "#61a8ff",
    "Nightmode_GoodColor": "#61ffb8",
    "Nightmode_HardColor": "#ffb861",
    "answer button width": "Normal", CHANGED
    "border radius": "1", CHANGED
    "button color": "hover",
    "button font size": "S",
    "button height": "S",
    "button width": "S",
    "confirmation": true,
    "confirmation time": 1200, CHANGED
    "confirmation x-offset": 0,
    "confirmation y-offset": 0,
    "style main screen buttons": true
}
```
Screenshot:
![image](https://user-images.githubusercontent.com/51046583/76478974-4c53f580-6430-11ea-9c77-795d1553234a.png)

**Comment by rishifter** [comment]
I've the same issue I am afraid. I'm on the latest version of Anki and dark mode is switched off from the Anki settings on Mac. System dark mode on/off doesn't make difference either.

**Comment by AnKingMed** [comment]
I think I found it. Just pushed an update. Please try that out and let me know if it does/doesn't work

**Comment by adix03** [comment]
Yeah, it's good now. Thanks a lot.
Just another thing, the "study" button is not customized.

**Comment by AnKingMed** [comment]
Can you send me a pic?

**Comment by adix03** [comment]
![image](https://user-images.githubusercontent.com/51046583/76593358-1db34900-651c-11ea-9ae8-b7e49f44014f.png)

**Comment by AnKingMed** [comment]
Thank you.  That button unfortunately isn't confirgured with this add-on because it involves a lot more coding that I don't yet understand (there's also some buttons in the add/edit screen and browser that aren't as well).  Maybe in the future!  But as of right now it looks like everything is functioning as I intended at least
