### ISSUE TITLE
Highlight color remains for too long after pressing button

### ISSUE THREAD

**Issue by Ooglogput** [AnKingMed/The-KING-of-Button-Add-ons#8]
![2020-03-15_10-54-40](https://user-images.githubusercontent.com/1039490/76699224-bd531180-66ab-11ea-9879-feb93e8b6dab.gif)

Should not overlay the Show Answer button.

**Comment by AnKingMed** [comment]
There is a way to configure how long the tooltip shows up in the config. Because it changes instantaneously, the gif you shared is how it actually intended to perform.  You can make it shorter if you'd prefer
